---

- name: Ensure python-pip is installed
  apt: name=python-pip state=present update_cache=yes

- name: Install dogstatsd via pip
  pip: name=dogstatsd-python state=present

- name: Ensure the datadog port 17123 is opened
  wait_for: port=17123 delay=2
  ignore_errors: True

- name: Ensure the dogstatsd port 8125 is opened
  wait_for: port=8125 delay=2
  ignore_errors: True