---
- name: Ensure datadog agent is started
  action: service name=datadog-agent state=started

- name: Configure the agent to connect the solr server
  template: src=datadog-solr.conf.j2 dest=/etc/dd-agent/conf.d/solr.yaml

- name: restart datadog
  action: service name=datadog-agent state=restarted

- name: Ensure the datadog port 17123 is opened
  wait_for: port=17123 delay=2
  ignore_errors: True