---
- name: Ensure pymongo package is present
  apt: name=python-pymongo state=present

- name: Create read-only user datadog
  mongodb_user: 
    database=admin 
    name=datadog 
    password={{datadog_mongo_user_pass}} 
    roles='read' 
    state=present

- name: Ensure datadog agent is started
  action: service name=datadog-agent state=started

- name: Configure the agent to connect the mongo server
  template: src=datadog-mongo.conf.j2 dest=/etc/dd-agent/conf.d/mongo.yaml

- name: restart datadog
  action: service name=datadog-agent state=restarted

- name: Ensure the datadog port 17123 is opened
  wait_for: port=17123 delay=2
  ignore_errors: True