---
- name: Nginx | Enable the status stub sites-available
  file:
    path: "{{nginx_dir}}/sites-enabled/nginx_status"
    src: "{{nginx_dir}}/sites-available/nginx_status"
    state: link
    force: yes

- name: Ensure datadog agent is started
  action: service name=datadog-agent state=started

- name: Configure the agent to connect the nginx server
  template: src=datadog-nginx.conf.j2 dest=/etc/dd-agent/conf.d/nginx.yaml

- name: restart datadog
  action: service name=datadog-agent state=restarted

- name: Ensure the datadog port 17123 is opened
  wait_for: port=17123 delay=2
  ignore_errors: True